#!/bin/bash

## FORSTWOOF UBUNTU PRESEED :: INSTALLATION SCRIPT

cd /var/tmp

set -e

# empty message of the day.
echo -n > /etc/motd

# remove some unused packages
DEBIAN_FRONTEND=noninteractive apt-get purge -y laptop-detect tasksel emacsen-common ienglish-common ispell

# install some additional packages
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends linux-headers-amd64 openssh-server sudo openssl zip unzip bzip2 vim vim-scripts curl whois net-tools strace lsof rsync git bash-completion gnupg software-properties-common tcpdump htop acl python3-pip ansible realmd sssd sssd-tools libnss-sss libpam-sss adcli samba-common-bin oddjob oddjob-mkhomedir packagekit

# install packages for join AD

realm discover essentia6.local > /tmp/ad
